KeyPair: "N Viginia" 
HqPublicIp : "52.26.103.3" 
HqPrivateIp : "10.0.1.121" 

VpcCidr : "10.1.0.0/16" 
PublicCidr : "10.1.0.0/24" 
PrivateCidr : "10.1.1.0/24" 

VcgIp : "10.1.0.100"
VcgServicePort : "6432"
InstanceType : "t2.micro"
ImageId : "ami-fce3c696"
IpsecConfigPath : "/home/ubuntu/ipsec/"
